[build]
  command = "sed -i 's|%%FIREBASE_API_KEY%%|'\"$FIREBASE_API_KEY\"'|g; s|%%FIREBASE_AUTH_DOMAIN%%|'\"$FIREBASE_AUTH_DOMAIN\"'|g; s|%%FIREBASE_DATABASE_URL%%|'\"$FIREBASE_DATABASE_URL\"'|g; s|%%FIREBASE_PROJECT_ID%%|'\"$FIREBASE_PROJECT_ID\"'|g; s|%%FIREBASE_STORAGE_BUCKET%%|'\"$FIREBASE_STORAGE_BUCKET\"'|g; s|%%FIREBASE_MESSAGING_SENDER_ID%%|'\"$FIREBASE_MESSAGING_SENDER_ID\"'|g; s|%%FIREBASE_APP_ID%%|'\"$FIREBASE_APP_ID\"'|g' hms-school.html"
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
